name: My First Automation

on:
  push:
    branches:
      - main
  pull_request:
    paths:
          - 'storybook/**'
  workflow_dispatch:
   

    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo this is for 
